site_name: Pancaik
site_description: Documentation for Pancaik
repo_url: https://github.com/jdorado/pancaik
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - tables
  - footnotes
nav:
  - Home: index.md
  - Features: features.md
  - Tasks: tasks.md
  - Server: server.md
  - Agents:
    - Overview: agents/index.md
    - TwitterAgent: agents/twitter_agent.md
  - Services:
    - Overview: services/index.md
    - Twitter Service: services/twitter.md
    - Creating Custom Tools: services/tools.md
  - Middleware:
    - Overview: middleware/index.md
    - X-Non-API Service: middleware/x-non-api.md
  - Examples:
    - Overview: examples.md
    - Framework Integrations:
      - Basic Agent: examples/basic_agent.md
      - LangGraph Integration: examples/langgraph_integration.md
      - CrewAI Integration: examples/crewai_integration.md
